export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST';
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS';
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL';

export const COURSE_FILTER_REQUEST = 'COURSE_FILTER_REQUEST';
export const COURSE_FILTER_SUCCESS = 'COURSE_FILTER_SUCCESS';
export const COURSE_FILTER_FAIL = 'COURSE_FILTER_FAIL';
