export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST';
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS';
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL';

export const COURSE_FILTER_REQUEST = 'COURSE_FILTER_REQUEST';
export const COURSE_FILTER_SUCCESS = 'COURSE_FILTER_SUCCESS';
export const COURSE_FILTER_FAIL = 'COURSE_FILTER_FAIL';


export const COURSE_DETAIL_REQUEST = 'COURSE_DETAIL_REQUEST';
export const COURSE_DETAIL_SUCCESS = 'COURSE_DETAIL_SUCCESS';
export const COURSE_DETAIL_FAIL = 'COURSE_DETAIL_FAIL';

export const COURSE_ENROLLED_REQUEST = 'COURSE_ENROLLED_REQUEST';
export const COURSE_ENROLLED_SUCCESS = 'COURSE_ENROLLED_SUCCESS';
export const COURSE_ENROLLED_FAIL = 'COURSE_ENROLLED_FAIL';

export const COURSE_WISHLIST_REQUEST = 'COURSE_WISHLIST_REQUEST';
export const COURSE_WISHLIST_SUCCESS = 'COURSE_WISHLIST_SUCCESS';
export const COURSE_WISHLIST_FAIL = 'COURSE_WISHLIST_FAIL';

export const COURSE_TOP_REQUEST = 'COURSE_TOP_REQUEST';
export const COURSE_TOP_SUCCESS = 'COURSE_TOP_SUCCESS';
export const COURSE_TOP_FAIL = 'COURSE_TOP_FAIL';

export const COURSE_CREATE_REQUEST = 'COURSE_CREATE_REQUEST';
export const COURSE_CREATE_SUCCESS = 'COURSE_CREATE_SUCCESS';
export const COURSE_CREATE_FAIL = 'COURSE_CREATE_FAIL';

export const COURSE_INSTRUCTOR_LIST_REQUEST = 'COURSE_INSTRUCTOR_LIST_REQUEST';
export const COURSE_INSTRUCTOR_LIST_SUCCESS = 'COURSE_INSTRUCTOR_LIST_SUCCESS';
export const COURSE_INSTRUCTOR_LIST_FAIL = 'COURSE_INSTRUCTOR_LIST_FAIL';

export const COURSE_UPDATE_REQUEST = 'COURSE_UPDATE_REQUEST';
export const COURSE_UPDATE_SUCCESS = 'COURSE_UPDATE_SUCCESS';
export const COURSE_UPDATE_FAIL = 'COURSE_UPDATE_FAIL';
export const COURSE_UPDATE_RESET = 'COURSE_UPDATE_RESET';